name: My first workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout the Repo
          uses: actions/checkout@v4
        - name: Welcome message
          run: |
            echo "Hi this is my first Github job"
            ls -lrta
            cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for a cover, I am a Dragon..... RAWR" >> dragon.txt 
        # - name: List the file in repo
        #   run: ls
            
        # - name: see the content in the file
        #   run: cat README.md