name: My first workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "Hi this is my first Github job"

        - name: List the file in repo
          run: ls
            
        # - name: see the content in the file
        #   run: cat README.md