name: Generate ASCII Artwork

on: 
  push

jobs:
  ascii_job: 
    runs-on: ubuntu-latest
    steps: 
    - name: checkout the repo
      uses: actions/checkout@v4

    - name: List files repo
      run: ls -ltra 

    - name: Executing ascii shell script
      run: |
       chmod +x .github/workflows/ascii-script.sh
       .github/workflows/ascii-script.sh
      

      