name: Generate ASCII Artwork

on: 
  push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps: 
    - name: Install cowsay program
      run: sudo apt-get install cowsay -y

    - name: Execute cowsay command
      run: cowsay -f dragon "Run for a cover, I am a Dragon..... RAWR" >> dragon.txt
    - name: sleep for 30 seconds
      run: sleep 30s

  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
    - name: sleep for 10 seconds
      run: sleep 10s
    
    - name: Test file exists
      run: grep -i "dragon" dragon.txt
      
  deployemet_job: 
    needs: test_job
    runs-on: ubuntu-latest
    steps:
    - name: Read file
      run: cat dragon.txt
    - name: list files
      run: ls -ltra
